import { Flex, Text, View, Image } from '@aws-amplify/ui-react';

export default function Example() {
  return (
  <Flex
    width="1440px"
    height="1024px"
    overflow="hidden"
    position="relative"
    backgroundColor="rgba(255,255,255,1)"
  >
    <Text
      fontFamily="Inter"
      fontSize="36px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="43.568180084228516px"
      textAlign="left"
      display="block"
      width="618px"
      height="176px"
      position="absolute"
      top="13px"
      left="542px"
      whiteSpace="pre-wrap"
    >
      Air Quality Hackathon

    </Text>
    <View
      width="472px"
      height="592px"
      display="block"
      position="absolute"
      top="163px"
      left="481px"
      backgroundColor="rgba(234,232,253,1)"
    />
    <Image
      width="134px"
      height="61px"
      display="block"
      position="absolute"
      top="948px"
      left="1267px"
      objectFit="cover"
      alt=""
    />
    <Text
      fontFamily="Inter"
      fontSize="14px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="16.94318199157715px"
      textAlign="left"
      display="block"
      width="82px"
      height="47px"
      position="absolute"
      top="63px"
      left="838px"
      whiteSpace="pre-wrap"
    >
      AcroSquad
    </Text>
    <Text
      fontFamily="Inter"
      fontSize="36px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="43.568180084228516px"
      textAlign="left"
      display="block"
      width="108px"
      height="46px"
      position="absolute"
      top="209px"
      left="605px"
      whiteSpace="pre-wrap"
    >
      Login
    </Text>
    <View
      width="235px"
      height="72px"
      display="block"
      position="absolute"
      top="304px"
      left="626px"
      backgroundColor="rgba(222,210,210,1)"
    />
    <Text
      fontFamily="Inter"
      fontSize="36px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="43.568180084228516px"
      textAlign="left"
      display="block"
      width="244px"
      height="96px"
      position="absolute"
      top="316px"
      left="654px"
      whiteSpace="pre-wrap"
    >
      UserName
    </Text>
    <View
      width="235px"
      height="72px"
      display="block"
      position="absolute"
      top="447px"
      left="626px"
      backgroundColor="rgba(222,210,210,1)"
    />
    <Text
      fontFamily="Inter"
      fontSize="36px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="43.568180084228516px"
      textAlign="left"
      display="block"
      width="244px"
      height="96px"
      position="absolute"
      top="459px"
      left="654px"
      whiteSpace="pre-wrap"
    >
      Password
    </Text>
    <View
      width="235px"
      height="73px"
      display="block"
      position="absolute"
      top="583px"
      left="626px"
      backgroundColor="rgba(138,128,254,1)"
    />
    <Text
      fontFamily="Inter"
      fontSize="36px"
      fontWeight="400"
      color="rgba(0,0,0,1)"
      lineHeight="43.568180084228516px"
      textAlign="left"
      display="block"
      width="244px"
      height="97px"
      position="absolute"
      top="594px"
      left="689px"
      whiteSpace="pre-wrap"
    >
      Login
    </Text>
  </Flex>
  )
}
